# Generated by Django 3.1.5 on 2021-03-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20210220_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='date_ob',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='place_ob',
        ),
    ]
